[project]
name = "ai-memos-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "logfire[fastapi]>=3.6.4",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.0",
]
